import type { Metadata } from "next";
// Assuming Geist and Geist_Mono are the correct imports for your fonts
import { Geist, Geist_Mono } from "next/font/google"; 
import "../globals.css";

// 1. Initialize fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// 2. Define metadata for SEO and browser tab title
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 3. Define the RootLayout component
// This component automatically wraps every page in your 'app' directory.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // This structure is correct and returns the necessary top-level HTML tags.
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}